config/routes.rb
Rails.application.routes.draw do
  root             to: 'pages#home'
  get 'login',     to: 'sessions#new'
  post 'login',    to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup',    to: 'users#new'

  resources :articles
  resources :users, except: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
    validates :name, presence: true
    validates :description, presence: true
    validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates :name, presence: true
  validates :email, presence: true

  has_secure_password
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_params, only: [:edit, :update, :show, :destroy]
  before_action :require_same_article, only: [:edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] = "Article successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article successfully deleted"
      redirect_to articles_path
    end
  end

  private

  def article_params
    params.require(:article).permit(:name, :description)
  end

  def set_params
    @article = Article.find(params[:id])
  end

  def require_same_article
    if current_user != @article.user
      flash[:notice] = "You are not competent for this article"
      redirect_to articles_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:notice] = "Welcome guest"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    log_out
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_params, only: [:edit, :update, :show]
 before_action :require_same_user, only: [:edit, :update, :destroy]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to our company"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destory
    @user = User.find(params[:id])
    if @user.destory
      flash[:notice] = "User successfully deleted"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_params
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:notice] = "You are competent just for your profile"
      redirect_to login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def log_out
    session[:user_id] = nil
    flash[:notice] = "Now you logged out"
    redirect_to root_path
  end

  def require_user
    if !logged_in?
      flash[:notice] = "you must be logged_in?"
      redirect_to root_path
    end
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="card">
    <div class="card-content">
      <p class="title">
        <%= article.name %>
      </p>
      <hr>
      <p class="subtitle">
        <%= article.description%>
      </p>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
        <span>
          <%= link_to 'View all', article_path(article)%>
        </span>
      </p>
    </footer>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="form">
<%= form_for @article do |f| %>
<%= render 'shared/error_messages', obj: @article %>
<div class="field">
  <%= f.label :name %>
  <div class="control has-icons-left has-icons-right">
    <%= f.text_field :name, class: "input is-success" %>
    <span class="icon is-small is-left">
      <i class="fas fa-user"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fas fa-check"></i>
    </span>
  </div>
</div>

<div class="field">
  <%= f.label :description %>
  <div class="control has-icons-left has-icons-right", id="area">
    <%= f.text_field :description, class:"textarea", column: "20"%>
    <span class="icon is-small is-left">
      <i class="fas fa-envelope"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fas fa-exclamation-triangle"></i>
    </span>
  </div>
</div>
  <div class="button-1">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="title", align="center">Edit</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 class="title", align="center"> All Articles </h1>
<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1 class="title", align="center"> New Article</h1>
<%= render 'form'%>

app/views/articles/show.html.erb
<div class="card">
  <header class="card-header">
    <p class="card-header-title">
    <h1 class="title"><%= @article.name %></h1>
    </p>
    <a href="#" class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </a>
  </header>
  <hr>
  <div class="card-content">
    <div class="content">
    <h2 class="subtitle"><%= @article.description %></h2>
  </div>
  <footer class="card-footer">
    <%= link_to 'Back', articles_path, class:"button is-info"%>
    <% if logged_in? &&  @article.user %>
      <%= link_to 'Edit', edit_article_path, class:"button is-warning" %>
      <%= link_to 'Delete', article_path, method: :delete, data: {confirm: "Are you sure?"},class:"button is-danger" %>
    <% end %>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-brand ">
  <%= link_to 'Home', root_path, class: "button is-info is-outlined" %>
  <%= link_to 'Articles', articles_path, class: "button is-info is-outlined" %>
  <%= link_to 'Sign up', signup_path, class: "button is-info is-outlined"  %>
  <% if logged_in? %>
    <%= link_to 'logout', logout_path, method: :delete, class: "button is-success"  %>
    <%= link_to 'Profile', user_path(current_user), class: "button is-info is-outlined" %>
  <% else %>
    <%= link_to 'login', login_path, class: "button is-success" %>
  <% end %>
  </div>
  <hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prov11</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <% if logged_in? %>
      <%= link_to 'Create Article', new_article_path, class: "button is-info is-outlined" %>
    <% end %>
    <%= render 'shared/flash'%>
    <%= yield %>
    <%= debug(params) if Rails.env.developmen? %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  The form contains <%= pluralize(obj.errors.count, "error") %>

  <ul>
    <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>

<%end%>

app/views/shared/_flash.html.erb
<% flash.each do |message_type,message| %>
  <div class="alert <%= message_type%> "><%= message %></div>
<%end%>

app/views/users/_form.html.erb
<div class="form">
<%= form_for @user do |f| %>
<%= render 'shared/error_messages', obj: @user %>
<div class="field">
  <%= f.label :name %>
  <div class="control has-icons-left has-icons-right">
    <%= f.text_field :name, class: "input is-success" %>
    <span class="icon is-small is-left">
      <i class="fas fa-user"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fas fa-check"></i>
    </span>
  </div>
</div>

<div class="field">
  <%= f.label :email %>
  <div class="control has-icons-left has-icons-right">
    <%= f.email_field :email, class: "input is-danger" %>
    <span class="icon is-small is-left">
      <i class="fas fa-envelope"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fas fa-exclamation-triangle"></i>
    </span>
  </div>
</div>

<div class="field">
  <%= f.label :password %>
  <div class="control has-icons-left has-icons-right">
    <%= f.password_field :password, class: "input is-danger" %>
    <span class="icon is-small is-left">
      <i class="fas fa-envelope"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fas fa-exclamation-triangle"></i>
    </span>
  </div>
</div>

<div class="field">
  <%= f.label :password_confirmation  %>
  <div class="control has-icons-left has-icons-right">
    <%= f.password_field :password_confirmation, class: "input is-danger" %>
    <span class="icon is-small is-left">
      <i class="fas fa-envelope"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fas fa-exclamation-triangle"></i>
    </span>
  </div>
</div>
  <div class="button-1">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1 class="title", align="center">Edit</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1 class="title", align="center"> Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
         User Name: <%= @user.name %>
      </h1>
    </div>
  </div>
  <br/><br/>
  <% if logged_in? && @user %>
  <%= link_to 'Edit', edit_user_path, class:"button is-warning" %>
</section>
<br/>
<%= render 'articles/article', obj: @user.articles %>
<%end%>